### ISSUE TITLE
ctsm lilac should use old shr_pio_mod.F90

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CESM_share#33]
The new version of shr_pio_mod.F90 used in cmeps uses NUOPC.  Lilac does not use nuopc and
needs to continue to use the older version.   This can be done by changing the line
https://github.com/ESCOMP/CESM_share/blob/main/buildlib.csm_share#L60  to be after line 71 iff lilac.  That is if you are doing a lilac build you want share/src in the Filepath before components/cmeps/cesm/nuopc_cap_share.
But if you are doing a cmeps build you do not want this.

**Comment by billsacks** [comment]
I'm returning to this issue. @jedwards4b your suggestion of changing the Filepath makes sense to me – thanks again for the suggestion. Before I do that, though, I want to better understand if this is a reasonable long-term solution, or if we'll need something else long-term.

Specifically: **What is the vision for the version of shr_pio_mod.F90 in the share code?** I imagine that currently its main use is to support cases with MCT. But what will happen when we drop MCT? Is the plan that this share code version of shr_pio_mod.F90 will be dropped at that point, or can you see maintaining that version indefinitely? Basically I'm wondering: If we tie the LILAC build to that version, are we just going to need to fix things again in a few months when that version is removed or no longer maintained?

@mvertens I want to bring you into the loop here, too.

**Comment by jedwards4b** [comment]
I would imagine that that version gets dropped when mct is dropped.  I think that for lilac it may be easiest not to use shr_pio at all and just write calls directly to pio.

**Comment by billsacks** [comment]
Thanks for these thoughts, @jedwards4b . Based on your input, I am going to try for a plan that won't involve any changes to the CESM_share repository. I am going to close this issue here and move further discussion back to https://github.com/ESCOMP/CTSM/issues/1759, where I'll welcome input on my proposed plan.

**Comment by billsacks** [comment]
I realized that my proposed plan won't work (see https://github.com/ESCOMP/CTSM/issues/1759#issuecomment-1171686549), so I think I'll need to do what @jedwards4b suggested initially.

This means that we'll need to maintain `shr_pio_mod` in the `share` repository just for the sake of LILAC even when MCT goes away, unless we can somehow change LILAC and/or the CMEPS version of `shr_pio_mod` so that those two can work together.

**Comment by billsacks** [comment]
The CESM_share piece of this fix came in with https://github.com/ESCOMP/CESM_share/pull/34
